export const DEFAULT_CONFIG_JSON = `{
  "$schema": "https://unpkg.com/lvlup@{{version}}/schema.json",
  "commit": true,
  "access": "public"
}`;

export const DEFAULT_README_MD = `# LvLup

Hello and welcome! This folder has been automatically generated by \`lvlup\`, a build tool that works
with single-package repos to help you version and publish your code. You can
find the full documentation for it [in our repository](https://github.com/talkohavy/lvlup)
`;
